import { API_URL } from "~/constants/utils";

const Api = {
  //user
  getListUser : (params) => API_URL + `/api/admin/user?${new URLSearchParams (params)}`,
  hideUser: (userId, id) => API_URL + `/api/admin/user/hide?userId=${userId}&id=${id}`,
  showUser: (userId, id) => API_URL + `/api/admin/user/show?userId=${userId}&id=${id}`,
  addEmp: () => API_URL + `/api/admin/user/addEmp`,
  detailAcc: (id) => API_URL + `/api/user/${id}`,
  updateUser: (id) => API_URL +`/api/user/update/${id}`,
  changePassword: (id) => API_URL + `/api/user/changePassword/${id}`,
  allUser: () => API_URL + `/api/admin/allUser`,
  //product
  getAllProduct: (params) => API_URL + `/api/admin/product?${new URLSearchParams (params)}`,
  createProduct : () => API_URL +`/api/admin/product/create`,
  updateProduct : () => API_URL +`/api/admin/product/update`,
  hideProduct : (id) => API_URL +`/api/admin/product/hide/${id}`,
  showProduct : (id) => API_URL +`/api/admin/product/show/${id}`,
  deleteProduct : (id) => API_URL +`/api/admin/product/delete/${id}`,
  detailProduct: (id) => API_URL + `/api/admin/product/${id}`,
  getProductSale: (id, keyword) => API_URL + `/api/admin/product/productSale?saleId=${id}&keyword=${keyword}`,
  getProductNoSale: (params) => API_URL + `/api/admin/product/productNoSale?${new URLSearchParams (params)}`,
  addProToSale: (id, productIds) => API_URL + `/api/admin/sale/add-product/${id}?productIds=${productIds}`,
  removeProSale: (id, productIds) => API_URL + `/api/admin/sale/remove-product/${id}?productIds=${productIds}`,
  //xóa ảnh product
  deleteProImages: (id) => API_URL +`/api/admin/productImage/delete/${id}`,
  
  //category
  detailCategory: (id) => API_URL + `/api/category/${id}`,
  getAllCategory: (params) => API_URL + `/api/admin/category?${new URLSearchParams (params)}`,
  getAllCategory2: () => API_URL + `/api/admin/category/allCategory`,
  getAllCategoryByParentId: (id) => API_URL + `/api/admin/category/parent?parentId=${id}`,
  hideCategory: (id) => API_URL + `/api/admin/category/hideCategory/${id}`,
  showCategory: (id) => API_URL + `/api/admin/category/showCategory/${id}`,
  deleteCategory: (id) => API_URL + `/api/admin/category/delete/${id}`,
  getParentCategory: () => API_URL + `/api/admin/category/parentCategory`,
  createCategory: () => API_URL + `/api/admin/category/create`,
  updateCategory: (id) => API_URL + `/api/admin/category/update/${id}`,
  //sale
  getSale : (id) => API_URL + `/api/admin/sale/${id}`,
  getAllSale : () => API_URL + `/api/admin/sale`,
  getAllSaleByKeyWord: (params) => API_URL + `/api/admin/sale?${new URLSearchParams (params)}`,
  hideSale: (id) => API_URL + `/api/admin/sale/hide/${id}`,
  showSale: (id) => API_URL + `/api/admin/sale/show/${id}`,
  deleteSale: (id) => API_URL + `/api/admin/sale/delete/${id}`,
  createSale: () => API_URL + `/api/admin/sale/create`,
  updateSale: (id) => API_URL + `/api/admin/sale/update/${id}`,
  //banner
  getAllBanner: (params) => API_URL + `/api/admin/banner/allBanner?${new URLSearchParams (params)}`,
  createBanner : () => API_URL +`/api/admin/banner/create`,
  updateBanner : () => API_URL +`/api/admin/banner/update`,
  hideBanner : (id) => API_URL +`/api/admin/banner/hideBanner/${id}`,
  showBanner : (id) => API_URL +`/api/admin/banner/showBanner/${id}`,
  deleteBanner : (id) => API_URL +`/api/admin/banner/delete/${id}`,
  detailBanner: (id) => API_URL + `/api/admin/banner/${id}`,
  //article
  getAllArticle: (params) => API_URL + `/api/admin/article?${new URLSearchParams (params)}`,
  createArticle : () => API_URL +`/api/admin/article/create`,
  updateArticle : (id) => API_URL +`/api/admin/article/update/${id}`,
  hideArticle : (id) => API_URL +`/api/admin/article/hide/${id}`,
  showArticle : (id) => API_URL +`/api/admin/article/show/${id}`,
  deleteArticle : (id) => API_URL +`/api/admin/article/delete/${id}`,
  detailArticle: (id) => API_URL + `/api/admin/article/${id}`,
  //order
  // getAllOrders: (page, keyword) => API_URL + `/api/admin/order/allOrder?page=${page}&keyword=${keyword}`,
  getAllOrders: (params) => API_URL + `/api/admin/order?${new URLSearchParams(params)}`,
  confirmOrder: () => API_URL + `/api/admin/order/confirm`,
  shippingOrder: () => API_URL + `/api/admin/order/shipping`,
  successOrder: () => API_URL + `/api/admin/order/success`,
  cancelOrder: () => API_URL + `/api/admin/order/empcancel`,
  upadteOrder: () => API_URL + `/api/admin/order/update`,
  getOrder: (id) => API_URL + `/api/admin/order/${id}`,
  //thông báo
  getNotification: () => API_URL + `/api/admin/load-notification`,
  readNotification: (id) => API_URL + `/api/admin/read-notification?id=${id}`,
  pushNotification: () => API_URL + `/api/admin/push-notification`,
  //thống kê
  getTotalSoldProduct: () => API_URL +`/api/admin/order/totalSold`,
  countOrders: (status) => API_URL + `/api/admin/order/countOrders?status=${status}`,
  totalProduct: () => API_URL + `/api/admin/product/totalProduct`,
  totalInCome: () => API_URL + `/api/admin/order/totalInCome`,
  totalOrderNoProcess: () =>  API_URL + `/api/admin/order/totalOrderNoProcess`,
  findTopUser: () => API_URL + `/api/admin/user/findTopUser`,
  getOrderByMonth: (status) => API_URL +`/api/admin/order/getOrderByMonth?status=${status}`,
}
export default Api;